# Generated by Django 6.0 on 2026-01-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='overall_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='AI模型的总体评分（0-10分）', null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='image_generation_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='图像生成能力评分（0-10分）', null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='information_query_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='信息查询能力评分（0-10分）', null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='study_assistance_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='学习辅助能力评分（0-10分）', null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value_for_money_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='性价比评分（0-10分）', null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='versatility_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='万能性评分（0-10分）', null=True),
        ),
    ]
