# Generated by Django 6.0 on 2026-01-07 16:28

from django.db import migrations, models
import django.db.models.deletion


def assign_default_user(apps, schema_editor):
    """为现有的 AITag 记录分配默认用户"""
    AITag = apps.get_model('backend', 'AITag')
    User = apps.get_model('backend', 'User')
    
    # 获取第一个用户作为默认用户
    default_user = User.objects.first()
    if default_user:
        # 为所有没有用户的 AITag 记录分配默认用户
        AITag.objects.filter(user__isnull=True).update(user=default_user)


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_reaction'),
    ]

    operations = [
        # 步骤1: 添加 user 字段（允许为空）
        migrations.AddField(
            model_name='aitag',
            name='user',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ai_tags',
                to='backend.user'
            ),
        ),
        # 步骤2: 为现有记录分配默认用户
        migrations.RunPython(assign_default_user, migrations.RunPython.noop),
        # 步骤3: 将字段改为非空
        migrations.AlterField(
            model_name='aitag',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ai_tags',
                to='backend.user'
            ),
        ),
        # 步骤4: 更新 unique_together 约束
        migrations.AlterUniqueTogether(
            name='aitag',
            unique_together={('ai', 'tag', 'user')},
        ),
    ]
