# Generated by Django 6.0 on 2026-01-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_add_user_to_aitag'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reaction',
            new_name='backend_rea_ai_id_3d45e5_idx',
            old_name='backend_re_ai_id_abc123_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='用户是否已激活（已废弃，默认True）'),
        ),
    ]
