from django.core.management.base import BaseCommand

from backend.models import AIModel


MODELS = [
    # 通用对话模型
    {
        "name": "ChatGPT",
        "developer": "OpenAI",
        "description": "OpenAI 开发的强大对话 AI，支持多种任务，从写作到编程辅助。包含 GPT-3.5、GPT-4 等版本。",
        "price": 0,
        "price_text": "免费 / $20/月",
        "official_url": "https://chat.openai.com",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    {
        "name": "Claude",
        "developer": "Anthropic",
        "description": "Anthropic 开发的 AI 助手，擅长长文本处理和代码分析。包含 Claude 2、Claude 3 等版本。",
        "price": 0,
        "price_text": "免费 / $20/月",
        "official_url": "https://claude.ai",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    {
        "name": "Gemini",
        "developer": "Google DeepMind",
        "description": "多模态通用助手，擅长搜索、推理、代码和多模态理解。包含 Gemini Pro、Gemini Ultra 等版本。",
        "price": 0,
        "price_text": "免费 / $19.99/月",
        "official_url": "https://gemini.google.com",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    {
        "name": "Perplexity",
        "developer": "Perplexity AI",
        "description": "AI 搜索引擎，结合搜索和 AI 回答，信息查询神器。",
        "price": 0,
        "price_text": "免费 / $20/月",
        "official_url": "https://www.perplexity.ai",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    {
        "name": "Grok",
        "developer": "xAI",
        "description": "强调实时信息检索与轻松语气的对话模型，适合快速问答和热点追踪。",
        "price": 0,
        "price_text": "订阅制",
        "official_url": "https://grok.x.ai",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    {
        "name": "Pi AI",
        "developer": "Inflection AI",
        "description": "面向日常聊天与知识问答的助手",
        "price": 0,
        "price_text": "免费 / 高级版收费",
        "official_url": "https://www.pi.ai",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    # 中文模型
    {
        "name": "文心一言",
        "developer": "百度",
        "description": "百度开发的中文大模型，支持多种问答与生成任务。包含 ERNIE 3.5、ERNIE 4.0 等版本。",
        "price": 0,
        "price_text": "免费 / 企业版收费",
        "official_url": "https://yiyan.baidu.com",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    {
        "name": "通义千问",
        "developer": "阿里巴巴",
        "description": "阿里巴巴开发的大语言模型，支持多轮对话和复杂任务。包含 Qwen-7B、Qwen-72B 等版本。",
        "price": 0,
        "price_text": "免费 / 企业版收费",
        "official_url": "https://tongyi.aliyun.com",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    {
        "name": "Kimi",
        "developer": "月之暗面",
        "description": "超长上下文中文助手，擅长阅读文档、总结与写作。",
        "price": 0,
        "price_text": "免费 / 会员",
        "official_url": "https://kimi.moonshot.cn",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    {
        "name": "智谱清言",
        "developer": "智谱AI",
        "description": "基于 GLM 大模型的中文对话助手，支持代码生成和数据分析。",
        "price": 0,
        "price_text": "免费 / 会员",
        "official_url": "https://chatglm.cn",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    {
        "name": "豆包",
        "developer": "字节跳动",
        "description": "字节跳动开发的多模态 AI 助手，支持文本、图像、语音交互。",
        "price": 0,
        "price_text": "免费 / 会员",
        "official_url": "https://www.doubao.com",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    # 图像生成模型
    {
        "name": "Midjourney",
        "developer": "Midjourney Inc.",
        "description": "最强大的 AI 图像生成工具，艺术创作首选。",
        "price": 0,
        "price_text": "$10/月起",
        "official_url": "https://www.midjourney.com",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    {
        "name": "DALL-E",
        "developer": "OpenAI",
        "description": "OpenAI 开发的图像生成模型，支持文本到图像转换。包含 DALL-E 2、DALL-E 3 等版本。",
        "price": 0,
        "price_text": "按使用量收费",
        "official_url": "https://openai.com/dall-e-3",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    {
        "name": "Stable Diffusion",
        "developer": "Stability AI & 社区",
        "description": "开源图像生成模型，可本地部署，免费使用。包含 SD 1.5、SDXL 等版本。",
        "price": 0,
        "price_text": "免费",
        "official_url": "https://stability.ai",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    {
        "name": "Firefly",
        "developer": "Adobe",
        "description": "为设计师优化的图片生成模型，与 Photoshop/Express 深度集成。",
        "price": 0,
        "price_text": "Creative Cloud 订阅内",
        "official_url": "https://www.adobe.com/sensei/generative-ai/firefly.html",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    {
        "name": "Leonardo.ai",
        "developer": "Leonardo.ai",
        "description": "专业的 AI 图像生成平台，提供多种风格和模型选择。",
        "price": 0,
        "price_text": "免费 / $10/月起",
        "official_url": "https://leonardo.ai",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    {
        "name": "Runway",
        "developer": "Runway",
        "description": "AI 视频和图像生成工具，支持文本到视频、图像编辑等功能。",
        "price": 0,
        "price_text": "免费 / $12/月起",
        "official_url": "https://runwayml.com",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    # 代码助手
    {
        "name": "GitHub Copilot",
        "developer": "GitHub",
        "description": "AI 代码补全工具，支持多种编程语言，提升编程效率。",
        "price": 0,
        "price_text": "$10/月",
        "official_url": "https://github.com/features/copilot",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    {
        "name": "Cursor",
        "developer": "Cursor",
        "description": "AI 驱动的代码编辑器，支持代码生成、重构和解释。",
        "price": 0,
        "price_text": "免费 / $20/月",
        "official_url": "https://cursor.sh",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    {
        "name": "Codeium",
        "developer": "Codeium",
        "description": "免费的 AI 代码补全工具，支持多种 IDE 和编程语言。",
        "price": 0,
        "price_text": "免费 / 高级版收费",
        "official_url": "https://codeium.com",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    # 开源模型
    {
        "name": "LLaMA",
        "developer": "Meta",
        "description": "大规模语言模型，用于研究和开发。包含 LLaMA 2、LLaMA 3 等版本。",
        "price": 0,
        "price_text": "免费 / 研究用途",
        "official_url": "https://ai.meta.com/llama",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    {
        "name": "Mistral",
        "developer": "Mistral AI",
        "description": "开源高性能语言模型。包含 Mistral 7B、Mixtral 8x7B 等版本。",
        "price": 0,
        "price_text": "免费 / 开源",
        "official_url": "https://www.mistral.ai/models",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    {
        "name": "OpenAssistant",
        "developer": "OpenAssistant",
        "description": "开源社区驱动的对话助手",
        "price": 0,
        "price_text": "免费 / 开源",
        "official_url": "https://open-assistant.io",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    # 其他工具
    {
        "name": "Notion AI",
        "developer": "Notion",
        "description": "集成在 Notion 中的 AI 助手，适合笔记和文档整理。",
        "price": 0,
        "price_text": "$10/月",
        "official_url": "https://www.notion.so/product/ai",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    {
        "name": "Jasper",
        "developer": "Jasper",
        "description": "AI 内容创作工具，适合营销文案、博客文章等写作任务。",
        "price": 0,
        "price_text": "$39/月起",
        "official_url": "https://www.jasper.ai",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
    {
        "name": "Copy.ai",
        "developer": "Copy.ai",
        "description": "AI 文案生成工具，支持多种营销和商务场景。",
        "price": 0,
        "price_text": "免费 / $36/月起",
        "official_url": "https://www.copy.ai",
        "avg_score": 0,
        "rating_count": 0,
        "favorite_count": 0,
    },
]


class Command(BaseCommand):
    help = "Seed AIModel table with sample models"

    def handle(self, *args, **options):
        created = 0
        for data in MODELS:
            obj, is_created = AIModel.objects.get_or_create(
                name=data["name"],
                defaults={
                    "developer": data.get("developer", ""),
                    "description": data.get("description", ""),
                    "price": data.get("price"),
                    "price_text": data.get("price_text", ""),
                    "official_url": data.get("official_url", ""),
                    "avg_score": data.get("avg_score", 0),
                    "rating_count": data.get("rating_count", 0),
                    "favorite_count": data.get("favorite_count", 0),
                },
            )
            created += 1 if is_created else 0

        self.stdout.write(self.style.SUCCESS(f"Seed completed. Created {created} AI models."))

